# -*- coding: utf-8 -*-
"""接口一句话说明。代码里的注释写的是「为什么这么做」，PRD 要的是「这个接口干什么」，
两者不能互相替代，所以这份表手写、与代码分开维护。"""
DOC = {
 "/login": "账号密码登录，返回 token 与身份信息",
 "/me": "取当前登录人的身份、所属组织",
 "/dict": "下发全部字典值域（国家、签证类别、人群、状态文案等）",

 "/shop/products": "选品列表：按国家/签证类型筛选在售产品，按下单渠道自动只看该端已审核通过的",
 "/shop/product": "产品详情：套餐报价、材料清单、服务保障、办理时长",

 "/order/create": "创建订单。校验套餐未停售、该端已审核上架；支持「先占单、24h 内补办签人资料」",
 "/order/pay": "支付订单。支付成功不等于放行，放行要等财务确认到账",
 "/order/info": "取订单的办签人资料录入进度与待补项",
 "/order/recv_addr": "取该订单对应供应商的收料地址",
 "/order/info/save": "保存办签人签证资料（护照、人群等），录齐后 info_done 置 1",
 "/order/cancel": "取消订单。已放行的单不能自助取消，须走退款",
 "/my/orders": "我的订单列表（客户 / 门店销售按各自数据边界）",
 "/my/last_contact": "取上次下单填的联系人，用于新单预填",
 "/my/travelers": "常用出行人档案列表",
 "/my/traveler/save": "新增 / 修改常用出行人",
 "/my/traveler/self": "把当前登录客户本人存为出行人",
 "/my/traveler/del": "删除常用出行人",
 "/my/addrs": "我的收货地址列表（原件寄回用）",
 "/my/addr/save": "新增 / 修改收货地址",
 "/my/addr/del": "删除收货地址",
 "/my/checklist": "客户端材料清单：按本人所属人群出，含已交/待交/被驳回及驳回原因",
 "/mat/upload": "上传某一项材料，上传后该项自动置「待审核」",
 "/my/supp": "查看本单的补料通知与缺项",

 "/fin/inbox": "财务待办：待确认到账的收款单",
 "/fin/receipts": "收款单列表",
 "/fin/receipt": "收款单详情",
 "/fin/audit": "收款单审核（金额、凭证是否对得上）",
 "/fin/voucher": "上传 / 查看到账凭证",
 "/fin/confirm": "确认到账并放行：置 ord.gate=1，工单下发供应商，履约动作解锁",
 "/fin/payables": "应付供应商列表",
 "/fin/pay": "对供应商付款出账",
 "/fin/advance": "垫付与代缴签证费台账",

 "/wo/list": "签证办理中心工单列表（UOM 视角，跨供应商全量）",
 "/wo/detail": "工单详情：办理进展、基础信息、材料清单、操作日志",
 "/mat/review": "逐项审核材料：通过 / 驳回，驳回必须填原因并原样下发客户",
 "/mat/passall": "一键通过该工单剩余待审材料",
 "/supp/create": "发起补料通知：列明缺项，客户端标红提示",
 "/progress/set": "推进办理进展 P1–P6，写操作日志",
 "/appt/save": "回填面签预约号、预约时间与地点",
 "/form/save": "保存官方申请表的填报结果（申请号、条码、缴费回执等）",
 "/task/list": "官方申请表填报任务列表",
 "/task/get": "取某个填表任务的题目与已填答案",
 "/task/prefill": "用办签人已有资料预填表单，减少重复录入",
 "/task/answer/save": "保存单题答案（边填边存）",
 "/task/submit": "客户 / 销售提交填表任务，转交顾问复核",
 "/task/confirm": "顾问复核确认，任务定稿",
 "/task/en/gen": "由中文答案生成英文译文（供官网填报用）",
 "/task/en/save": "保存人工校正后的英文译文",
 "/task/unconfirm": "撤销定稿，退回可编辑状态",
 "/task/official": "导出官网填报用的对照清单（人工照着录入官网）",
 "/task/share": "生成免登录填表分享链接与二维码，发给客人自己填",

 "/pub/task/upload": "免登录分享链接：客人上传材料",
 "/pub/task/save": "免登录分享链接：客人保存填表答案",
 "/fee/save": "回填签证费缴纳金额与回执号",
 "/batch/list": "送签批次列表",
 "/batch/create": "新建送签批次，把若干办签人合并递交",
 "/batch/send": "批次递交：记录递交方式与时间，办签人进入「待出结果」",
 "/result/save": "登记签证结果。字段随结果动态变化：出签填签证号与有效期，拒签填原因与分类，行政审查填截止日",
 "/liability/set": "拒签责任判定：我司 / 客户 / 使领馆，决定退款口径",
 "/deliver/create": "创建交付记录（签证结果交付客户）",
 "/deliver/sign": "客户签收确认",
 "/deliver/list": "交付记录列表",
 "/wo/hold": "工单挂起（已下线，保留接口兼容历史数据）",
 "/wo/assign": "改派工单经办人（UOM 侧）",

 "/lead/board": "主管看板：各专员负载、逾期工单、拒签归因",

 "/refund/apply": "发起退款申请，可按办签人选择",
 "/refund/quote": "试算退款金额（随人数与责任判定变化）",
 "/refund/list": "退款单列表",
 "/refund/detail": "退款单详情",
 "/refund/approve": "退款审批：通过 / 驳回并填原因",
 "/refund/pay": "退款出账，订单转「已退款」",

 "/sup/products": "供应商产品列表（含两端审核状态与上架开关）",
 "/sup/pkg/save": "保存套餐报价（改价会自动下架并重新送审）",
 "/sup/orders": "供应商订单概览",
 "/sup/orderlist": "供应商订单列表",
 "/sup/assign": "改派工单经办人（供应商侧，指派本供应商计调）",
 "/sup/members": "本供应商可被指派的经办人名单",
 "/sup/progress": "供应商回传办理进展",
 "/sup/settle": "供应商结算查询",
 "/sup/prepays": "供应商预付款列表",
 "/sup/bills": "供应商月度账单",
 "/sup/refunds": "供应商退款列表",
 "/sup/refund/act": "供应商处理退款（确认 / 驳回）",

 "/sup/addrs": "收料地址列表",
 "/sup/addr/save": "新增 / 修改收料地址",
 "/sup/addr/del": "删除收料地址",

 "/sup/groups": "渠道组与加价策略列表",
 "/sup/group/save": "保存渠道组与加价规则（含结算价高于零售价的报价倒挂预警）",
 "/sup/group/del": "删除渠道组",

 "/sup/catalog": "平台产品目录：供应商上品时先在目录里选国家+签证类型",
 "/sup/product/create": "新增产品第一步：录签证属性并绑定国家送签材料库清单版本",
 "/sup/product/save": "保存产品信息（改材料清单会自动下架并重新送审）",
 "/sup/pkg/add": "新增套餐",
 "/sup/mat/custom": "在平台清单基础上生成本供应商自有版材料要求",
 "/sup/pkg/status": "套餐启停售",
 "/sup/pkg/del": "删除套餐",

 "/sup/pub": "渠道投放：选定上架范围（B 端 CSP / C 端小程序）",
 "/sup/pub/batch": "批量投放",
 "/sup/pub/price": "投放价格调整",

 "/shop/policies": "客户端签证政策内容",
 "/ops/policies": "签证政策内容列表",
 "/ops/policy/save": "保存签证政策内容",
 "/ops/policy/del": "删除签证政策内容",

 "/ops/samples": "材料样例库列表（跨国复用的示意图）",
 "/ops/sample/save": "保存材料样例",
 "/ops/sample/del": "删除材料样例",
 "/ops/formvers": "国家签证表模板列表",
 "/ops/formver": "表模板详情与题目",
 "/ops/formver/save": "保存表模板",
 "/ops/formver/toggle": "表模板启用 / 禁用（只有这两个状态，送签材料库只能引用启用中的）",
 "/ops/form/field/save": "保存表模板题目",
 "/ops/form/field/del": "删除表模板题目",
 "/ops/form/tpl": "导入官方表结构生成题目",
 "/ops/fullvers": "国家送签材料库列表（含关联签证产品数，可跳转产品管理并自动筛选）",
 "/ops/fullver": "清单版本详情与逐项材料",
 "/ops/fullver/save": "保存清单版本（改生效日期生成新版本，否则原地修改）",
 "/ops/fullver/regen": "按人群重新生成清单项",
 "/ops/fullver/publish": "发布清单版本（版本级状态：待发布 / 已发布 / 已撤回）",
 "/ops/fullver/del": "删除清单版本",
 "/ops/item/save": "保存清单里的一项材料",
 "/ops/item/del": "删除清单里的一项材料",
 "/ops/products": "签证产品管理列表（B/C 端各一张，字段按端分叉）",
 "/ops/product": "产品详情 / 审核页数据",
 "/ops/product/onsale": "销售状态启停售开关",
 "/ops/product/market": "保存对客文案（名称、副标题、标签、卖点、主图、分享推广语）",
 "/ops/product/review": "产品审核：通过 / 驳回，按 track 区分 B 端与 C 端，互不影响",
 "/ops/orders": "订单总览（运营视角）",
 "/order/detail": "订单详情",
 "/ops/countries": "国家展示配置列表",
 "/ops/country/save": "保存国家展示配置",
 "/ops/country/del": "删除国家展示配置",
 "/ops/home": "C 端首页配置",
 "/ops/home/save": "保存首页配置项",
 "/ops/home/del": "删除首页配置项",
 "/ops/home/sort": "首页配置项排序",
 "/pub/home": "客户端首页数据（免登录）",
 "/ops/stats": "运营数据统计",
 "/crm/customers": "客户档案列表",
 "/crm/customer": "客户档案详情（历史订单、办签人、地址）",
 "/crm/addr/save": "保存客户地址",
 "/crm/addr/del": "删除客户地址",
 "/events": "操作日志查询（谁在什么时候把什么改成了什么）",
 "/my/track": "客户端进度查询",
 "/my/order/detail": "客户端订单详情",
 "/api/upload": "文件上传（图片 / PDF，限白名单扩展名）",
 "/api/qr": "把文本渲染成二维码 SVG（分享填表链接给客人扫）",
}
